<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Users_model extends CI_Model
{

    public $table = 'users';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
	
	function get_by_id_obj($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table);
    }
	
	function detail_users_row($id)
	{
		 $this->db->where($this->id, $id);
         $a = $this->db->get($this->table);
		 return $a->row_array();
	}
    
	function check_email($email)
	{	
		$str = "SELECT * FROM users WHERE email = '$email'  ";
		$q = $this->db->query($str);
		$f = $q->row_array();
		
		return $f;
	
		//$this->db->where("email",$email);
		//return $this->db->get($this->table)->row_array();
	}
	
	function check_email2($email,$check_email)
	{
		$str = "SELECT * FROM users WHERE email = '$email' AND email <> '$check_email'  ";
		$q = $this->db->query($str);
		$f = $q->row_array();
		
		return $f;
		
	}
	
	function check_password($username,$pass)
	{
		$pass = password_hash($password,PASSWORD_BCRYPT);
		
		$str = "SELECT * FROM users WHERE email = '$username' AND password = '$pass' ";
		$q = $this->db->query($str);	
		$f = $q->row_array();
		
		return $f;
	}
	
	function update_password($username,$new_pass)
	{
		$pass =  password_hash($password,PASSWORD_BCRYPT);
		
		$str = "UPDATE users SET password = '$new_pass' WHERE email = '$username' ";
		$q = $this->db->query($str);
		
		return $q;
		
	}
	
	function update_photo($username,$photo_name)
	{
		$str = "UPDATE users SET photo = '$photo_name' WHERE email = '$username' ";
		$q = $this->db->query($str);
		
		return $q; 	
	}
	
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('role', $q);
	$this->db->or_like('kode', $q);
	$this->db->or_like('photo', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
		$this->db->or_like('name', $q);
		$this->db->or_like('email', $q);
		$this->db->or_like('role', $q);
		$this->db->or_like('kode', $q);
		$this->db->or_like('photo', $q);
		$this->db->or_like('password', $q);
		$this->db->or_like('created_at', $q);
		$this->db->or_like('updated_at', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Users_model.php */
/* Location: ./application/models/Users_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-12-13 16:34:18 */
/* http://harviacode.com */