<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Opex_account_model extends CI_Model
{

    public $table = 'opex_ms';
    public $id = 'no_acc_opex';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $aa = $this->db->get($this->table)->row_array();
		return $aa;
    }
	
	function get_by_id_row($id)
	{
		$str = "SELECT * FROM ".$this->table." WHERE ".$this->id." = '$id' ";
		$q = $this->db->query($str);
		$f = $q->row_array();
		
		return $f;
	}
	
	function check_account($no_acc_opex)
	{
		$str = "SELECT * FROM opex_ms WHERE no_acc_opex = '$no_acc_opex' ";
		$q   = $this->db->query($str);
		$f   = $q->row_array();
		
		return $f;  	
		
	}
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no_acc_opex', $q);
		//$this->db->or_like('account_name', $q);
		$this->db->or_like('detail', $q);
		$this->db->or_like('aktivasi', $q);
		$this->db->or_like('controllable', $q);
		$this->db->or_like('cost_pool', $q);
		$this->db->or_like('description', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no_acc_opex', $q);
		//$this->db->or_like('account_name', $q);
		$this->db->or_like('detail', $q);
		$this->db->or_like('aktivasi', $q);
		$this->db->or_like('controllable', $q);
		$this->db->or_like('cost_pool', $q);
		$this->db->or_like('description', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        //$this->db->where($this->id, $id);
        //$this->db->update($this->table, $data);
		
		$str  = "UPDATE opex_ms SET  					    ";
		$str .= "no_acc_opex		= '$data[no_acc_opex]' ,";
		$str .= "account_name		= '$data[account_name]',";
		$str .= "detail				= '$data[detail]'	   ,";
		$str .= "aktivasi			= '$data[aktivasi]'	   ,";
		$str .= "controllable		= '$data[controllable]',";
		$str .= "cost_pool			= '$data[cost_pool]'   ,";
		$str .= "description		= '$data[description]'  ";
		
		$str .= "WHERE no_acc_opex	= '$data[no_acc_opex2]'	";
		
		//echo $str; exit;
		
		$a = $this->db->query($str);
		return $a;
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Opex_ms_model.php */
/* Location: ./application/models/Opex_ms_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-12-13 17:42:51 */
/* http://harviacode.com */